first commit

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -12,6 +12,23 @@ pipeline {
       }
     }
 
+    stage('Install Terraform') {
+      steps {
+        script {
+          sh '''
+            if ! [ -x "$(command -v terraform)" ]; then
+              echo "Terraform not found. Installing..."
+              curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
+              unzip terraform_1.0.0_linux_amd64.zip
+              sudo mv terraform /usr/local/bin/
+            else
+              echo "Terraform is already installed."
+            fi
+          '''
+        }
+      }
+    }
+
     stage('Terraform Init and Apply') {
       steps {
         dir('terraform') {
